-- CreateTable
CREATE TABLE `Registration` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `yearOfEntry` VARCHAR(191) NOT NULL,
    `childFirstName` VARCHAR(191) NOT NULL,
    `childLastName` VARCHAR(191) NOT NULL,
    `childNameUsed` VARCHAR(191) NULL,
    `childDobDay` VARCHAR(191) NOT NULL,
    `childDobMonth` VARCHAR(191) NOT NULL,
    `childDobYear` VARCHAR(191) NOT NULL,
    `childGender` VARCHAR(191) NOT NULL,
    `homeStreetAddress` VARCHAR(191) NOT NULL,
    `homeAddressLine2` VARCHAR(191) NULL,
    `homeCity` VARCHAR(191) NOT NULL,
    `homeCounty` VARCHAR(191) NULL,
    `homePostcode` VARCHAR(191) NOT NULL,
    `homeCountry` VARCHAR(191) NOT NULL,
    `parent1Title` VARCHAR(191) NULL,
    `parent1FirstName` VARCHAR(191) NOT NULL,
    `parent1LastName` VARCHAR(191) NOT NULL,
    `parent1Relationship` VARCHAR(191) NOT NULL,
    `parent1Mobile` VARCHAR(191) NOT NULL,
    `parent1Email` VARCHAR(191) NOT NULL,
    `parent1Occupation` VARCHAR(191) NULL,
    `parent1WorkStreetAddress` VARCHAR(191) NULL,
    `parent1WorkAddressLine2` VARCHAR(191) NULL,
    `parent1WorkCity` VARCHAR(191) NULL,
    `parent1WorkCounty` VARCHAR(191) NULL,
    `parent1WorkPostcode` VARCHAR(191) NULL,
    `parent1WorkCountry` VARCHAR(191) NULL,
    `parent2Title` VARCHAR(191) NULL,
    `parent2FirstName` VARCHAR(191) NULL,
    `parent2LastName` VARCHAR(191) NULL,
    `parent2Relationship` VARCHAR(191) NULL,
    `parent2Mobile` VARCHAR(191) NULL,
    `parent2Email` VARCHAR(191) NULL,
    `parent2Occupation` VARCHAR(191) NULL,
    `parent2WorkStreetAddress` VARCHAR(191) NULL,
    `parent2WorkAddressLine2` VARCHAR(191) NULL,
    `parent2WorkCity` VARCHAR(191) NULL,
    `parent2WorkCounty` VARCHAR(191) NULL,
    `parent2WorkPostcode` VARCHAR(191) NULL,
    `parent2WorkCountry` VARCHAR(191) NULL,
    `schoolTourAttended` VARCHAR(191) NULL,
    `healthConditions` VARCHAR(191) NULL,
    `previousSchool` VARCHAR(191) NULL,
    `otherChildrenAges` VARCHAR(191) NULL,
    `childrenAlreadyAttending` VARCHAR(191) NULL,
    `nationality` VARCHAR(191) NULL,
    `ethnicOrigin` VARCHAR(191) NULL,
    `languageAtHome` VARCHAR(191) NULL,
    `socialCareInvolvement` VARCHAR(191) NULL,
    `furtherInformation` TEXT NULL,
    `hearAboutSchool` VARCHAR(191) NULL,
    `feesAgreement` BOOLEAN NOT NULL DEFAULT false,
    `withdrawalAgreement` BOOLEAN NOT NULL DEFAULT false,
    `lmsSynced` BOOLEAN NOT NULL DEFAULT false,
    `lmsSyncError` TEXT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
